require('tap')(function(test)
  local readdirRecursive = require('../lib/luvit-read-directory-recursive').readdirRecursive
  test('Test if we can recursively read directories', function(expect)
    readdirRecursive('./testDir', function(err, files)
      local cb = expect(function()
        assert(err == nil, 'Error should be nil')
        assert(#files == 2, 'There should be two test files')
      end)
      cb()
    end)
  end)

  test('Test if we handle non existent directories properly', function(expect)
    readdirRecursive('./nonExistantTestDir', function(err, files)
      local cb = expect(function()
        assert(err == 'ENOENT: no such file or directory: ./nonExistantTestDir', 'Error should be:  ENOENT: no such file or directory: ./nonExistantTestDir')
        assert(files == nil, 'Files should be nil')
      end)
      cb()
    end)
  end)
end)
